### ISSUE TITLE
Are Foldseek-uesd Databases uncomplete from alphafold2 or uniprot

### ISSUE THREAD

**Issue by yang-nei** [steineggerlab/foldseek#107]
I blast a structure, and there are many blasted structrue showed, however, lack of the structure I threw in(lack of 100% seq id.). Then, I've verfied the data again by uniprot, and there is exeisting the protein  I throw in  with 100% seq id. My question is , whether is there uncomplete databases exeisted in foldseek or, your algorithms ,MMseq2 can explain this  Phenomenon ?

**Comment by yang-nei** [comment]
I've re tested pdb downloaded by uniprot  and the same Phenomenon shows again.

**Comment by martin-steinegger** [comment]
Without a proper explanation of your workflow, we can not help you.

**Comment by yang-nei** [comment]
<img width="1440" alt="截圖 2023-04-13 上午6 43 01" src="https://user-images.githubusercontent.com/122717414/231602369-4d3a3a6e-39bb-4288-9928-d3a79972ef07.png">

**Comment by yang-nei** [comment]
I use ENH82046 this protein structure to run foldseek, results as following,

**Comment by yang-nei** [comment]
<img width="559" alt="截圖 2023-04-13 上午6 47 43" src="https://user-images.githubusercontent.com/122717414/231602805-ec5036ee-2d57-4676-84b9-0f31f1b4c770.png">

**Comment by yang-nei** [comment]
<img width="1138" alt="截圖 2023-04-13 上午6 48 21" src="https://user-images.githubusercontent.com/122717414/231602879-6c27f937-7057-4893-ba68-1815d75057c6.png">

**Comment by yang-nei** [comment]
And uniprot databases exeisting ENH82046 protein structure, however , when I use foldseek for search such proteins, lack of this protein. In theory 100% seq id. , with super highly similarity of structures. Nevertheless, I can't find it by foldseek. Not only this but also exeisting the same other proteins.

**Comment by yang-nei** [comment]
So,  my question  is  Whether Foldseek took advantage of MMseq2 can't search all of the alphafold2 databases and searched results are unable to elucidate representing to all the alphafold2 predicted structures?

**Comment by milot-mirdita** [comment]
Is N4VM52 the query you search with and it doesn't find hits that you expect it should?
If so, what Uniprot sequence do you expect it to find?

Or do you have a query structure that should find N4VM52 and it doesn't?
If so, what is your query structure?

It's quite hard to say what is going on since there are many possible explanations still. E.g.:
* On the foldseek server, we offer only a clustered version of the AlphaFoldDB, thus not all hits can be found. Only the cluster representative can be found.
* We have implemented steps to suppress false positives. Foldseek was tuned to find hits in the same Family/Superfamily/Fold and not just things that looks similar. That might also get rid of hits.

**Comment by yang-nei** [comment]
I downloaded database from Enseblfungi for sequences databases, and cleavage signal peptide with signP 5.0 ,then take advantage of Colabfold to predict its protein structure. Then, I just threw in Foldseek for structure blast. In theory, the pdb. I threw in is the same protein to N4VM52 without singal peptide.

**Comment by yang-nei** [comment]
I've threw in N4VM52 itself , however, still can't find itself by foldseek

**Comment by milot-mirdita** [comment]
N4VM52 was clustered into a cluster with https://www.uniprot.org/uniprotkb/A0A6G1JF11 as the representative (with 90% bi-directional coverage and 50 seq-id thresholds). Thus it can't directly be found.

If you want to search the full Uniprot I recommend downloading Foldseek and the full afdb locally and execute the search there.

**Comment by yang-nei** [comment]
Another question, Once I download foldseek, it just can search protein homologous by blasting all of Alphafold2 database without any limitions or there is any limitations

**Comment by martin-steinegger** [comment]
Check this please https://github.com/steineggerlab/foldseek/wiki#memory-requirements
